### ISSUE TITLE
Add in reference to example in harvesting toolkit as well as tools

### ISSUE THREAD

**Issue by dcwalk** [datarefuge/workflow#14]
It looks like some detail got cut from the [docs update](https://github.com/datarefugephilly/workflow/commit/d8f0c8bbc7c3aa83bf2cb53770d6e3876457a4ef) which we added in based on questions feedback, in particular:
- [ ] link out to example of what a harvested link looks like
- [x] reference tools more concretely
- ~~unclear why claiming on spreadsheet was cut, or am I missing it? Seems important with new master uncrawlable list~~

**Comment by librlaurie** [comment]
@dcwalk - I'm not sure how to address this one. Is there a suggestion you have?

**Comment by dcwalk** [comment]
This meant the example that b5 added, the text got cut out during a documentation rewrite. Closing as the text has changed significantly since then
