### ISSUE TITLE
Incorporate DataRescueA2 Day 1 Harvesting notes

### ISSUE THREAD

**Issue by dcwalk** [datarefuge/workflow#17]
- Helpful commandline tools
  - jQ parsing json
  - developers tools for chrome, inspect, requests, "copy as curl" (sessionID etc..) (useful for ajax, js )
when populating data)
  - ruby gem watir (uses selenium) allows programmatic browsing the page
- Think about FTP downloading -- many have the same hostname, can FTP and dld everything but hard to track downloaded downloads
  - (i.e. grabbing noaa ftp)
  - youtube dlding python script
- mirroring FTPs downloaded

- Current status 3 projects to end today
  - Data Dictionary of EPA db description
  - Odd NOAA Files
  - JS search (broken) driven by json, pulling PDF

- Some prospective bigger projects identified for tomorrow

**Comment by vielmetti** [comment]
- `jq` parsing JSON is https://stedolan.github.io/jq/
- developers tools for Chrome: ???
- Ruby gem `watir` https://watir.com
- `youtube-dl` is a tool for downloading, in Python http://rg3.github.io/youtube-dl/

**Comment by dcwalk** [comment]
Thanks @vielmetti , incorporating this into #20 now! :)

**Comment by dcwalk** [comment]
Addressed by #20
