### ISSUE TITLE
Break this into multiple documents in this repo. 

### ISSUE THREAD

**Issue by librlaurie** [datarefuge/workflow#2]

**Comment by dcwalk** [comment]
Hey! Is there a way we can collaborate in getting the stuff that will be relevant for future events into this repo of @b5's? https://github.com/edgi-govdata-archiving/harvesting-toolkit

We've been reviewing and documenting there and it would be awesome to have that synthesized :)

**Comment by librlaurie** [comment]
This one is done, right @dcwalk ?

**Comment by dcwalk** [comment]
I didn't open the issue, closing as addressed. We can reopen if needed
