### ISSUE TITLE
Clean up Workflow Overhaul

### ISSUE THREAD

**Issue by dcwalk** [datarefuge/workflow#26]
- [x] @b5 re: no checker upload needed. They will use the same uploader as the harvester
 - [x] All Tabs of the spreadsheet should be pluralized (Checkers, etc.)
 - [x] Checker status indicator → Rename Checker Handle or something like that? 
   - [x] Same would apply to all roles
 - [x] Could we choose a slightly lighter green for the Uncrawlable spreadsheet
  - [x] Make sure we have a form for harvesters and researchers (for remote ones)
 - [x] Make sure that all the Slack channels corresponding to the roles exist and are named properly.
- [x] Add new fields for researchers claim/status
   - [x] Done/not done: “Done” value should be triggered either by the Describer adding a Closed status
   - [x] BUT ALSO by the Researcher entering “yes” in  “Can this be crawled” cell ping @swipp

Larger/more important issues:
- [x] Have we solved whether each event will have one designated S3 sys admin?
- [x] Confirm whether we keep every event in folders within the same bucket or not

**Comment by swipps** [comment]
I can't check boxes, so here's what I have done:
All Tabs of the spreadsheet should be pluralized (Checkers, etc.)
Checker status indicator → Rename Checker Handle or something like that?
 Same would apply to all roles
Could we choose a slightly lighter green for the Uncrawlable spreadsheet - I think I did this?

Other:
 Done/not done: “Done” value should be triggered either by the Describer adding a Closed status
 BUT ALSO by the Researcher entering “yes” in “Can this be crawled” cell ping @swipp

^^Those are already how I have them set up in the spreadsheet. Closed items move on if they are not crawlable. If they are, they go straight into the Done/Not Done sheet.

QUESTIONS:
Add new fields for researchers claim/status - I do not understand this. Feel free to DM me @swipp

----
This is all done in TEMPLATE; I am moving the changes over to the other spreadsheets as we speak.

**Comment by dcwalk** [comment]
@swipps Invite sent to the org, I think that allows you to edit! Regardless, I've hopefully updated accurately :)

**Comment by dcwalk** [comment]
Updated to show Google Form exists!

**Comment by dcwalk** [comment]
I'm closing this for now as the overhaul was completed.
