### ISSUE TITLE
partners, links language

### ISSUE THREAD

**Issue by titaniumbones** [datarefuge/workflow#31]
not to flog a dead horse @librlaurie but your mods to my language in the README represent the datarescue project **as part of datarefuge**. I don't think that's accurate, so I'm not sure why you would introduce that error.  I would be happy to correct.  In future maybe you can go through the PR process when you revert commits that have been approved? 

psyched to see you tomorrow!

**Comment by librlaurie** [comment]
Tried again.

**Comment by khdelphine** [comment]
I have now merged in the new version of that paragraph.  

Are we good now?

**Comment by librlaurie** [comment]
Hey @titaniumbones just want to make sure you're ok with the current state of things on this.

**Comment by titaniumbones** [comment]
I like it a lot better. I'd draw your attention to the subject-object relationship in the final para. Otherwise much improved.

**Comment by librlaurie** [comment]
Thanks for calling my attention to that. I fixed that and issued a pull request, in case i missed something. But, I suspect it's better now.
