### ISSUE TITLE
Form link in README broken

### ISSUE THREAD

**Issue by nicku33** [datarefuge/workflow#32]
By asking your DataRescue guide or by filling out **this form**
Link broken.

**Comment by dcwalk** [comment]
@khdelphine can we address the form links?

**Comment by librlaurie** [comment]
I can't find this link in the main readme. Can you be more specific?

**Comment by dcwalk** [comment]
Here they are @librlaurie : https://github.com/datarefuge/workflow/search?utf8=%E2%9C%93&q=%28Link+coming+soon%29

**Comment by khdelphine** [comment]
Hi, 

Yes, those are "fixed" by the latest merge, in the sense that it is now recast as getting an account in http://www.archivers.space/ and we leave it to the organizers to figure out how to do this: "The organizers of the event (in-person or remote) will tell you how to volunteer for the Harvester role, either through slack or a form.
As a result, they will send you an invite to the Archivers app, which helps us coordinate all the data archiving work we do."

Brendan was recommending that the organizers just paste an invite into a slack DM for each participant, but I don't know if that will always be done that way. 

Does that work?

**Comment by khdelphine** [comment]
I am closing this, but feel free to reopen if needed.
