### ISSUE TITLE
describe app process

### ISSUE THREAD

**Issue by titaniumbones** [datarefuge/workflow#33]
SFBay needed a quick & dirty workflow writeup for the app, so I put one up here: 

https://github.com/edgi-govdata-archiving/workflow

feel free to pull! But it occurs to me that this repo has been doing double duty as 
(a) *a full spec for building a verifiable upload chain* and 
(b) doucmentation for event volunteers.I think that may be hard for a single repo to do. The event volunteers need a simpler/shorter set of docs that they can consult quickly. So my branch also takes a bunch of stuff out of the repo... Is not final, but as I said, SFBay needed something in a hurry.

**Comment by librlaurie** [comment]
We're going to stick with this one, @titaniumbones. Delphine has been updating this to reflect the app, though, now that Brendan and I talked through the plans for it. We'd love to work with you to fold some of your changes in, if you'd like.

**Comment by minisaez1** [comment]
@titaniumbones We're also looking for "quick and dirty" for the volunteers - something that fits on a A/V display during the event.  If you have / create such an animal, please share with Data Rescue Boulder - would be appreciated! (and glad to give you credit)

**Comment by titaniumbones** [comment]
@minisaez1 not quite that small but the workflow repo in he edgi-govdsta-archiving github org is kind of a shortened  version of this report. You could modify it further and use. See the datarescuenyc repo in there for another model. Look at the datarescuebayarea fork of the NYC repo for a hybrid. Sorry on a train or would find the links.
