### ISSUE TITLE
What are the technical requirements to run the Chrome extension?

### ISSUE THREAD

**Issue by dorasmith** [datarefuge/workflow#41]
Eg, what is the minimum version of Chrome the Chrome extension for nominating sites as crawlable or uncrawlable works in, what OS's and devices does it work on, is java required and if so what version, does javascript have to be enabled, anything else the Chrome extension needs to work?

One reason to care is that Chrome can only be updated to a certain point in some versions of Linux.   Though for all I know the version of Chrome has nothing to do with whether it works.  

And is it supposed to work on Android?   Is there a particular trick to getting it to work on Android?

I don't know if this is the appropriate place to ask, but I've been trying different methods of asking and trying to learn who to ask, without success.   Matt Price says "file an issue in the repo and ask there", but I've no clue what that means.   There are issues here, so maybe this is the repo!

**Comment by dcwalk** [comment]
Hey @dorasmith, thanks for asking the question!--- I see that you asked in the repo where we do development on the extension. That might be the best place to continue this conversation, so I'm closing here for now.
