### ISSUE TITLE
remove harvesting tools

### ISSUE THREAD

**Issue by titaniumbones** [datarefuge/workflow#47]
as harvesting tools are actively being developed in https://github.com/edgi-govdata-archiving/harvesting-tools/, require broader developer access than is appropriate for these documents, and are related to a pretty distinct skillset from the skills needed to update this repo, I suggest removing the harvesting tools from the repo.  CF https://github.com/edgi-govdata-archiving/workflow/commit/47da83df7087c4818e25c72c7732f504d72288e6 and https://github.com/edgi-govdata-archiving/workflow/commit/d4fb29f17ce46f0d75790a4f5cf37699b6b4f529, which could probably be cherrypicked from the edgi fork. .

**Comment by titaniumbones** [comment]
(instead of cherrypicking you could just:
```sh
git rm -r --cached harvesting-toolkit
mv harvesting-toolkit/README.md harvesting.md
git add harvesting.md
```
and then update links in the repo's readme)

**Comment by librlaurie** [comment]
ok. done. issued pull request.
