### ISSUE TITLE
describe account cred s in more detail

### ISSUE THREAD

**Issue by titaniumbones** [datarefuge/workflow#6]
What accounts are we talking about? Who needs them? Different groups probably need different versions.

**Comment by dcwalk** [comment]
Yeah, there is a line RE: credentials, but would be good to provide an example of what those could look like. I'm assuming s3 right now?

**Comment by khdelphine** [comment]
I will try to add some more info, but note that there is so much we can say about credentials in a completely public documentation. 

For now, some of this information must be provided by event organizers, and we are working on a way to pass on credentials to remote participants.

**Comment by titaniumbones** [comment]
but if you can say something general about it so that organizers know
who to ask for creds, etc...

**Comment by khdelphine** [comment]
I believe we have moved past this, so I am going to close it. But feel free to reopen if needed.
