### ISSUE TITLE
Change the doc section file names to work areas

### ISSUE THREAD

**Issue by dcwalk** [datarefuge/workflow#60]
Right now the files (and URLs generated as a result) are mostly subject gerunds (e.g., "https://datarefuge.github.io/workflow/harvesting/") but there are some outliers (advance work, coordinator work, research, metadata, index [but this one has to stay for mkdocs])

advance-work.md
bagging.md
checking.md
coordinator-work.md
harvesting.md
index.md 
metadata.md
research.md
seednsort.md

In the overview sections are referred to by role (i.e., Harvesters, Baggers)

Can we pick one and be consistent with how the pages are referenced? My vote would be to have the page urls/headings describe the area of work ("researching"), not the role ("researcher")

**Comment by khdelphine** [comment]
@dcwalk: I think that DataRefuge folks like referring to roles (Harvester, Checker, Bagger, Describer) quite a bit. I know that personally it is my preference.  I feel that it is conceptually useful to keep track of all the different functions, and make sure that some roles do not end up being minimized and treated as an afterthought (e.g., even though they might not yet be fully represented in the app, Checker being an example of that.).  

This being said, it is true that the role based headers do not match the file names, which predate the focus on roles. Is that important enough to change the file names?

@librlaurie, @MarJanzer, what do you think?

**Comment by dcwalk** [comment]
From a usability perspective I think it is important enough to be consistent. If we are calling it researcher but the URL says "researching" that is a needless point of friction.

**Comment by MarJanzer** [comment]
I don't think it's super confusing to have them not match, but stylistically it would be preferred. Can we make them all in noun form though?

**Comment by khdelphine** [comment]
Ok, we can make everything match. 

I think that using gerunds everywhere is ok, as long as we can still use the roles names in the body of the text. For instance in the overview:

**************
3. Harvesting
Harvesters take the "uncrawlable" data and try to figure out how to actually capture it based on the recommendations of the Researchers. Etc...
**************

How does that sound?

**Comment by dcwalk** [comment]
Sounds great to me :)

**Comment by khdelphine** [comment]
Note that I did not change the advance-work.md and coordinator-work.md, which might anyway need to be changed quite a bit in one way or another.
