### ISSUE TITLE
Drop "Sorters" from "Seeders/Sorters"

### ISSUE THREAD

**Issue by dcwalk** [datarefuge/workflow#63]
As I understand the task we have sort of moved away from the "sorting" aspect, and tend to refer to this area as "seeding," can we remove the " 'n sorters" and "/sorters" to be a bit cleaner with our role descriptions?

**Comment by titaniumbones** [comment]
That matches my experience e at events. @kdelphinr I think you've been to events I haven't, what's your take?

On February 21, 2017 10:49:32 AM EST, dcwalk <notifications@github.com> wrote:
>As I understand the task we have sort of moved away from the "sorting"
>aspect, and tend to refer to this area as "seeding," can we remove the
>" 'n sorters" and "/sorters" to be a bit cleaner with our role
>descriptions?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/datarefuge/workflow/issues/63

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by khdelphine** [comment]
Yes, dropping Sorters sounds fine to me.
