### ISSUE TITLE
Update Seeding, Researching, and Harvesting for Chrome extension and Archivers app

### ISSUE THREAD

**Issue by dcwalk** [datarefuge/workflow#66]
These sections are not _quite_ in sync with the tools interfaces any more, 2 guides were created that are more current, can we merge these improvements upstream?

I was wondering if anyone had time to merge in the instructions from the [SFbay gdoc](https://docs.google.com/document/d/1crJcDk_PKUBp2HgEZc1T2P4LOwNBup2GixSaFd5NFFw/edit#) and out of date fork on the EDGI repo, in particular three pages:
- [b4ba16c4/harvesting.md](https://github.com/edgi-govdata-archiving/workflow/blob/a74d73a6310f8eb0c900f8aa8f311db6b4ba16c4/harvesting.md)
- [b4ba16c4/research.md](https://github.com/edgi-govdata-archiving/workflow/blob/a74d73a6310f8eb0c900f8aa8f311db6b4ba16c4/research.md)
- [b4ba16c4/seednsort.md](https://github.com/edgi-govdata-archiving/workflow/blob/a74d73a6310f8eb0c900f8aa8f311db6b4ba16c4/seednsort.md)

**Comment by dcwalk** [comment]
@suchthis here is the issue I set up for tackling a documentation update!

**Comment by titaniumbones** [comment]
Can we also add a "post-event" section, currently in
https://github.com/edgi-govdata-archiving/workflow/blob/master/README.md
at the bottom of the page?

**Comment by khdelphine** [comment]
@titaniumbones, I just added an "After the event" section following your recommendation (it will come up in my next PR).

**Comment by dcwalk** [comment]
Also this-- WEB ARCHIVING FAQ
https://docs.google.com/document/d/1XJaSQHDwGX7e2UCCE0WFKrD-1x9qnLb5RKkkpSZqp9o/edit

**Comment by dcwalk** [comment]
Changes was merged in addressing this issue, closing
