### ISSUE TITLE
Add Archivers app FAQ to workflow docs

### ISSUE THREAD

**Issue by dcwalk** [datarefuge/workflow#67]
We should have a separate section with FAQ for the Archivers app, these came out of the issues @b5, @danielballan and @titaniumbones noticed out of last weekend's events. Currently here: https://edgi-govdata-archiving.github.io/guides/archivers-faq/ but I think they should be moved to these docs

**Comment by khdelphine** [comment]
This is a great idea. I can try to take care of it tomorrow.  (Unless someone beats me to it.)
