### ISSUE TITLE
Decide on "lieutenant" team for the repo or at list of people who can merge PRs.

### ISSUE THREAD

**Issue by khdelphine** [datarefuge/workflow#74]

**Comment by dcwalk** [comment]
@khdelphine I can be added from EDGI

**Comment by dcwalk** [comment]
I think @titaniumbones would be the other natural fit in terms of EDGI person coordinating github contributors.

**Comment by khdelphine** [comment]
Ok, sounds good. I can add your names tonight.

**Comment by dcwalk** [comment]
Just pinging on this -- where are these listed? (and should they be formalized into something like a team?

**Comment by khdelphine** [comment]
@dcwalk The names are listed on https://github.com/datarefuge/workflow/blob/master/CONTRIBUTING.md

There are 4 names at this time, although a couple of other people merge PR for all practical purposes (e.g. @rlappel). 

Having a formal github team sounds good, but I have never created one. @librlaurie, would you like us to take this approach? @dcwalk recommends it for clarity.

**Comment by librlaurie** [comment]
Sure. A team is fine with me. I've made it, and added these folks. Let me know if that works. Thanks

**Comment by dcwalk** [comment]
The people who merge PRs are on @datarefuge/workflow, updating the Contributing Guidelines via #86
