### ISSUE TITLE
add poster crawlable/uncrawlable poster?

### ISSUE THREAD

**Issue by jschell42** [datarefuge/workflow#78]
do we want to add the poster that lists out things that are crawlable/uncrawlable to the site?

https://drive.google.com/file/d/0B8Gv3Zy5ceY3X0xiSlV2dnhMYWc/view

**Comment by khdelphine** [comment]
That sounds like a good idea, but where would you like to see it listed? Should it be a separate item in the TOC or just a link in one of the main sections?

**Comment by dcwalk** [comment]
This has been addressed in #87
