### ISSUE TITLE
Update Seeders documentation to reflect that the End of Term Harvest has ended

### ISSUE THREAD

**Issue by dcwalk** [datarefuge/workflow#93]
The End of Term Harvest has ended!! We submitted over 90,000 urls as seeds 🎉
However, we need to update the documentation before the events this weekend to reflect that we are no longer submitting them to the EoT, but instead to Internet Archive

**Comment by janetriley** [comment]
@dcwalk  is this what you had in mind?  [pull request #94 here](https://github.com/datarefuge/workflow/pull/94)

**Comment by dcwalk** [comment]
Thanks for your quick work @janetriley :)) I left a comment on the PR

**Comment by dcwalk** [comment]
Fixed!
